version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g @ionic/cli
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ionic build --prod
artifacts:
  files:
    - '**/*'
  base-directory: www